/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnnotationTool: typeof import('./components/AnnotationTool.vue')['default']
    DynamicLegends: typeof import('./components/legends/DynamicLegends.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconArrowDown: typeof import('@element-plus/icons-vue')['ArrowDown']
    ElIconArrowLeft: typeof import('@element-plus/icons-vue')['ArrowLeft']
    ElIconArrowUp: typeof import('@element-plus/icons-vue')['ArrowUp']
    ElIconClose: typeof import('@element-plus/icons-vue')['Close']
    ElIconEdit: typeof import('@element-plus/icons-vue')['Edit']
    ElIconWarning: typeof import('@element-plus/icons-vue')['Warning']
    ElIconWarningFilled: typeof import('@element-plus/icons-vue')['WarningFilled']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTree: typeof import('element-plus/es')['ElTree']
    ExternalResourceCard: typeof import('./components/ExternalResourceCard.vue')['default']
    FlatmapVuer: typeof import('./components/FlatmapVuer.vue')['default']
    MultiFlatmapVuer: typeof import('./components/MultiFlatmapVuer.vue')['default']
    ProvenancePopup: typeof import('./components/ProvenancePopup.vue')['default']
    SelectionsGroup: typeof import('./components/SelectionsGroup.vue')['default']
    SvgLegends: typeof import('./components/legends/SvgLegends.vue')['default']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
    TreeControls: typeof import('./components/TreeControls.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
    vPopover: typeof import('element-plus/es')['ElPopoverDirective']
  }
}
